version: "3"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:            
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - host
  
  angular:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: angular:latest
    container_name: angular-app 
    command: bash -c "npm instal && npm run prod"
    working_dir: /root/app
    tty: true
    depends_on:
      - proxy
    volumes:
      - ./:/root/app
    ports:
      - 3000:3000
    networks:
      - host

networks:
  host: